/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ggalmazor

import com.ggalmazor.days.Day1

class AdventOfCode {
    fun run() {
        listOf(Day1()).forEach {
            println(it.partOne())
            println(it.partTwo())
        }
    }
}

fun main() {
    AdventOfCode().run()
}
