/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ggalmazor

import kotlin.test.Test
import kotlin.test.assertNotNull

class AdventOfCodeTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = AdventOfCode()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
